<?php
/**
 * Copyright (c) 2018. Ghiya <ghiya@mikadze.me>
 */

namespace ghiyam\apix;


use ghiyam\apix\controller\ServiceController;
use ghiyam\apix\exceptions\ClientRequestException;
use ghiyam\apix\query\Query;
use ghiyam\apix\query\QueueBuilder;
use yii\base\InvalidConfigException;
use yii\base\Module;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * Class APIx
 *
 *
 * @package ghiyam\apix
 * @version v0.1.0
 */
class APIx extends Module
{


    /**
     * @var Service[]
     */
    private $_services = [];


    /**
     * {@inheritdoc}
     */
    /*public function bootstrap($app)
    {

    }*/


    /*public function init()
    {
        parent::init();
        \Yii::configure($this, require __DIR__ . '/config/config.php');
    }*/


    public function runAction($route, $params = [])
    {
        return parent::runAction($route, $params); // TODO: Change the autogenerated stub
    }


    /**
     * @return \yii\console\Controller|\yii\web\Controller|ServiceController
     */
    protected function getServiceController()
    {
        return \Yii::$app->controller;
    }


    /**
     * @param array $serviceParams
     *
     * @return Service
     */
    public function getServiceWithParams($serviceParams = [])
    {
        $instanceHash = md5(Json::encode($serviceParams));
        if (!isset($this->_services[$instanceHash])) {
            $this->_services[$instanceHash] = new Service($serviceParams);
        }
        return $this->_services[$instanceHash];
    }


    /**
     * @var string|array
     */
    private $_fetchResult;

    /**
     * @param array $queryParams
     *
     * @return array|bool|null|string
     * @throws ClientRequestException
     * @throws InvalidConfigException
     * @throws \ErrorException
     */
    public function fetch($queryParams = [])
    {
        $queue = QueueBuilder::build($queryParams);
        $lastResponse = null;
        while (!$queue->isEmpty()) {
            // send query
            $query = $queue->dequeue();
            $query = $this->getServiceController()->sendQuery($query);
            $lastResponse = $query->fetched;
            // if composed query
            if ($query->isComposed()) {
                // several queries
                if (ArrayHelper::isIndexed($query->join)) {
                    $joinResult = "";
                    foreach ($query->join as $index) {
                        $joinResult .= " " .
                            $this
                                ->fetchComposed(
                                    $queue->dequeue(),
                                    $query->fetched
                                );
                    }
                    return trim($joinResult);
                }
                // single query
                else {
                    return
                        $this
                            ->fetchComposed(
                                $queue->dequeue(),
                                $query->fetched
                            );
                }
            }
        }
        return isset($query) ? $query->fetched : null;
    }

    /*protected function hasJoinIndex() {
        return preg_match("/{\w}+/i", implode(":", array_values($joinQuery['params'])));
    }*/

    /**
     * @param array $joinIndex
     * @param array $joinQuery
     * @param array $fetchResult
     *
     * @return null|array|string
     * @throws ClientRequestException
     * @throws InvalidConfigException
     * @throws \ErrorException
     */
    protected function fetchComposed(Query $joinQuery, $fetchResult = [])
    {
        $joinQuery->fetched = $fetchResult;

        if (isset($fetchResult)) {
            $joinParams = [];
            if (preg_match("/\*/i", $joinIndex[1])) {
                $joinParams =
                    [
                        'params' =>
                            [
                                $joinIndex[0] => $fetchResult
                            ]
                    ];
            }
            else {
                if (isset($fetchResult[$joinIndex[1]])) {
                    // search in method
                    if (preg_match("/{\w}+/i", $joinQuery['method'])) {

                    }
                    // search in params
                    /*elseif( preg_match("/{\w}+/i", implode(":", array_values($joinQuery['params']))) ) {

                    }*/
                    // join by default
                    else {
                        $joinParams =
                            [
                                'params' =>
                                    [
                                        $joinIndex[0] => $fetchResult[$joinIndex[1]]
                                    ]
                            ];
                    }
                }
                else {
                    throw new \ErrorException("Improper `joinIndex` value.");
                }
            }
            return
                $this->fetch(
                    ArrayHelper::merge(
                        $joinParams,
                        $joinQuery
                    )
                );
        }
        throw new \ErrorException("Cannot join request with `null` response.");
    }
    /*protected function fetchComposed($joinIndex = [], $joinQuery = [], $fetchResult = [])
    {
        if (isset($fetchResult)) {
            $joinParams = [];
            if (preg_match("/\/i", $joinIndex[1])) {
                $joinParams =
                    [
                        'params' =>
                            [
                                $joinIndex[0] => $fetchResult
                            ]
                    ];
            }
            else {
                if (isset($fetchResult[$joinIndex[1]])) {
                    // search in method
                    if (preg_match("/{\w}+/i", $joinQuery['method'])) {

                    }
                    // search in params
                    elseif( preg_match("/{\w}+/i", implode(":", array_values($joinQuery['params']))) ) {

                    }
                    // join by default
                    else {
                        $joinParams =
                            [
                                'params' =>
                                    [
                                        $joinIndex[0] => $fetchResult[$joinIndex[1]]
                                    ]
                            ];
                    }
                }
                else {
                    throw new \ErrorException("Improper `joinIndex` value.");
                }
            }
            return
                $this->fetch(
                    ArrayHelper::merge(
                        $joinParams,
                        $joinQuery
                    )
                );
        }
        throw new \ErrorException("Cannot join request with `null` response.");
    }*/

}